site_name: AppImage Updater
site_description: A service for automating finding and downloading AppImage applications
site_url: https://royw.github.io/appimage-updater
repo_url: https://github.com/royw/appimage-updater
repo_name: royw/appimage-updater

copyright: Copyright &copy; 2024 Roy Wright

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: material/home
  favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22><path d=%22M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z%22/></svg>

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: timeago
      timezone: America/Chicago
      locale: en
      fallback_to_build_date: true
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_submodules: false
            show_source: true
            show_bases: false
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            filters: ["!^_"]
            show_root_toc_entry: false
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      default_lang: python
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/royw
      name: Roy Wright on GitHub
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - User Guide:
    - Installation: installation.md
    - Getting Started: getting-started.md
    - Configuration: configuration.md
    - Commands: commands.md
    - Examples: examples.md
  - Development:
    - Contributing: contributing.md
    - Architecture: architecture.md
    - Testing: testing.md
  - API Reference: reference/
  - Changelog: changelog.md

  - Technical Documentation:
    - Theme Files: theme-files.md
    - Color Files: color-files.md

  - Project Information:
    - Project Overview: project-files/README.md
    - Developer Guide: project-files/DEV-README.md
    - License: license.md

watch:
  - src/appimage_updater
