version: '3'

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - uv sync

  typecheck:
    desc: Run type checking with mypy
    cmds:
      - uv run mypy {{.CLI_ARGS | default "src/"}}

  lint:
    desc: Run linting with ruff
    cmds:
      - uv run ruff check {{.CLI_ARGS | default "src/"}}

  format:
    desc: Format code with ruff
    cmds:
      - uv run ruff format {{.CLI_ARGS | default "src/"}}

  test:
    desc: Run tests with pytest
    cmds:
      - uv run pytest {{.CLI_ARGS}}

  complexity:
    desc: Analyze code complexity with radon
    cmds:
      - uv run radon cc {{.CLI_ARGS | default "src/ --min C"}}

  check:
    desc: Run all code quality checks
    deps:
      - typecheck
      - lint
      - complexity
      - test

  run:
    desc: Run the application
    cmds:
      - uv run python -m appimage_updater {{.CLI_ARGS}}

  clean:
    desc: Clean up generated files
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
      - rm -rf .mypy_cache/
      - rm -rf .pytest_cache/
      - rm -rf dist/
      - rm -rf build/

  dev:
    desc: Set up development environment
    deps:
      - install
    cmds:
      - echo "Development environment ready!"

  default:
    desc: Show available tasks
    cmds:
      - task --list
